EN-20803 - only set cheetahRevision when we cut a release (#6091)
EN-20803 - only set cheetahRevision when we cut a release
  also preserve cheetah revision in the cherry-pick and hotfix cases

diff --git a/frontend/bin/build b/frontend/bin/build
--- a/frontend/bin/build
+++ b/frontend/bin/build
@@ -45,23 +45,42 @@ gem install httparty -v '0.15.6'
 # Write REVISION file
 git rev-parse HEAD > "${WORKSPACE}/frontend/REVISION"
 
-# write current Cheetah revision to a file
+# make sure Cheetah tests stay in-sync with their environments
+# set a new cheetah revision only when we cut a release
+# preserve existing cheetah revision in the cherry-pick and hotfix cases
+# don't bother setting cheetah revision if staging build since this only applies to RC/EU/Fedramp
+# fail build if something goes wrong so we don't cause Cheetah tests to get out of sync with environments
+#   in the event that this fails and you need to get a hotfix out
+#   you can override by unsetting RELEASE_MODE in the frontend-build-release job
+#   see: https://jenkins-build.socrata.com/view/frontend-release-pipeline/job/frontend-build-release/configure
+if [ -n "$RELEASE_MODE" ]; then
+  echo "$RELEASE_MODE release detected"
 
-cheetah_revision_file="${WORKSPACE}/frontend/CHEETAH_REVISION"
+  if [ $RELEASE_MODE == 'cut' ]; then
+    echo 'retrieving Cheetah revision from api.github'
+    cheetah_revision=$(curl -sH "Authorization: token $GITHUB_API_TOKEN" \
+      https://api.github.com/repos/socrata/cheetah/branches/master | jq -r '.commit.sha')
+  elif [ $RELEASE_MODE == 'cherry-pick' ]; then
+    echo 'retrieving Cheetah revision from RC /version'
+    cheetah_revision=$(curl -s https://cheetah.rc-socrata.com/version.json | jq -r '.cheetahRevision')
+  elif [ $RELEASE_MODE == 'hotfix' ]; then
+    echo 'retrieving Cheetah revision from Fedramp /version'
+    cheetah_revision=$(curl -s https://cheetah.demo.socrata.com/version.json | jq -r '.cheetahRevision')
+  else
+    echo "ERROR >> unrecognized release mode $RELEASE_MODE"
+    echo 'failing build since this would cause Cheetah tests to get out of sync with environments'
+    exit 1
+  fi
 
-# get current SHA from HEAD:master
-echo 'Getting latest Cheetah revision from api.github...'
-current_cheetah_revision=$(curl -sH "Authorization: token $GITHUB_API_TOKEN" \
-  https://api.github.com/repos/socrata/cheetah/branches/master | jq -r '.commit.sha')
-
-# will return "null" if $GITHUB_API_TOKEN not set/incorrect OR in the rare case of object not found
-# assure file is removed in this case and downstream logic will set cheetahRevision to ''
-if [ $current_cheetah_revision == "null" ]; then
-  echo 'WARNING >> Call to api.github failed. Make sure $GITHUB_API_TOKEN is set. cheetahRevision will get set to empty string'
-  rm -f $cheetah_revision_file
-else
-  echo "Recording current Cheetah revision: $current_cheetah_revision to $cheetah_revision_file"
-  echo $current_cheetah_revision > $cheetah_revision_file
+  if [[ $cheetah_revision =~ [a-f0-9]{40} ]]; then
+    cheetah_revision_file="${WORKSPACE}/frontend/CHEETAH_REVISION"
+    echo "writing Cheetah revision: $cheetah_revision to $cheetah_revision_file"
+    echo $cheetah_revision > $cheetah_revision_file
+  else
+    echo "ERROR >> Cheetah revision: $cheetah_revision is not SHA-like"
+    echo 'failing build since this would cause Cheetah tests to get out of sync with environments'
+    exit 1
+  fi
 fi
 
 # Package assets
